//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_Class.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Grade = new HashSet<Grade>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string Tea_Name { get; set; }
        public string ClassRoom { get; set; }
        public Nullable<System.DateTime> SchoolTime { get; set; }
        public int TeacherID { get; set; }
        public Nullable<System.TimeSpan> NewTime { get; set; }
        public string SchoolYear { get; set; }
        public string Term { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grade { get; set; }
    }
}
