//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_Class.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public string Stu_Number { get; set; }
        public Nullable<decimal> Stu_Score { get; set; }
        public int CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
