//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_Class.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Stu_Namber { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_Sex { get; set; }
        public string Stu_Photo { get; set; }
        public string Stu_Password { get; set; }
        public string IDCard { get; set; }
        public string Nation { get; set; }
        public string NativePlace { get; set; }
        public string PoliticsStatus { get; set; }
        public string Phone { get; set; }
        public string EnrollmentYear { get; set; }
        public string SchoolRoll { get; set; }
        public int Class_ID { get; set; }
        public int CourseID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Course Course { get; set; }
    }
}
