//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du_Class.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Grade = new HashSet<Grade>();
        }
    
        public int StudentID { get; set; }
        public string Stu_Namber { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_Sex { get; set; }
        public string Stu_Photo { get; set; }
        public string Stu_Password { get; set; }
        public string IDCard { get; set; }
        public string Nation { get; set; }
        public string NativePlace { get; set; }
        public string PoliticsStatus { get; set; }
        public string Phone { get; set; }
        public string EnrollmentYear { get; set; }
        public string SchoolRoll { get; set; }
        public Nullable<int> Class_ID { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grade { get; set; }
    }
}
